security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    
  role_hierarchy:
    ROLE_ADMIN:         ROLE_USER
    ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
  
  providers:
    app_users:
      memory:
        users:
          user:   { password: userpass, roles [ 'ROLE_USER' ] }
          admin:  { password: adminpass, roles [ 'ROLE_ADMIN' ] }

  firewalls:
    main:
      pattern: ^/
      form_login:
        provider: app_users
        csrf_token_generator: security.csrf.token_manager
        login_path: login
        check_path: login
      anonymous:    true
      logout:
        path:   logout
        target: login

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/webcrawler-response, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/search-pages/search, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/search-pages/more-like-this, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/search-pages/autocomplete, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/search-api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/search-api/v2, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/drupal/ctexport, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/reco/reco.js, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/reco/report, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/reco/get, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/searchapi, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/search-client, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, role: ROLE_ADMIN }